version: '3'
services:
  fastapi:
    image: tilkec23/audio-fastapi
    ports:
      - "8000:8000"
    networks:
      my-network:
  mongodb:
    image: mongo:4.4.6
    container_name: audio-mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      my-network:

volumes:
  mongodb-data:

networks:
  my-network: